reminder-interval: 300

reminder-message: '&dIf you encounter a bug, please report it! \n&b/bugreport <title> <description>'

report-message: '&bThanks for reporting!'

delete-message: '&aReport deleted'

noperm-message: '&cYou do not have access to this command!'

join-message: true

auto-update: true
