# This is the interval between each message in seconds
reminder-interval: 300

# Define the message you want to send to the players
reminder-message: "&dIf you encounter a bug, please report it! \n&b/bugreport <title> <description>"

# Disable or Enable auto updating
auto-update: true

#Bug report message
pmessage: "§bThanks for reporting!"

